### ISSUE TITLE
[UI] need 404.html & 50x.html

### ISSUE THREAD

**Issue by robturtle** [tech-gamers/side-project-incubator-web#6]
- [ ] `public/404.html`
- [ ] `public/50x.html`
- bonus: make 50x.html polymorphic by its status code

**Comment by wangtjwork** [comment]
Will there be a need for public/404.html or public/50x.html? We're routing all requests to index.html in Nginx config, so no 404 on nginx side, and 500 could only happen when Nginx is down right? If Nginx is down even when we provide a 50x page, it could not be served then.

If we route all requests to index.html, we should be adding error handling in React Routes instead of public/404 or 50x
